### ISSUE TITLE
Warnings in Ruby 2.4

### ISSUE THREAD

**Issue by skyzyx** [marcandre/backports#104]
```
/root/.gem/ruby/2.4.0/gems/backports-3.6.8/lib/backports/1.8.7/fixnum/div.rb:1: warning: constant ::Fixnum is deprecated
/root/.gem/ruby/2.4.0/gems/backports-3.6.8/lib/backports/1.8.7/fixnum/fdiv.rb:1: warning: constant ::Fixnum is deprecated
/root/.gem/ruby/2.4.0/gems/backports-3.6.8/lib/backports/2.1.0/bignum/bit_length.rb:1: warning: constant ::Bignum is deprecated
/root/.gem/ruby/2.4.0/gems/backports-3.6.8/lib/backports/2.1.0/fixnum/bit_length.rb:1: warning: constant ::Fixnum is deprecated
```

http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

**Comment by marcandre** [comment]
Fixed, thanks

**Comment by skyzyx** [comment]
When do you expect this patch to make its way into a release?

**Comment by marcandre** [comment]
@skyzyx already released! IMO, any bug fix justifies a release...

**Comment by skyzyx** [comment]
Amazing. Thank you!

**Comment by tilthouse** [comment]
This is still not on rubygems. Can you publish? 
![backports___rubygems_org___your_community_gem_host](https://cloud.githubusercontent.com/assets/22075/24416422/9964969e-1399-11e7-8b11-aad0b3997bb6.png)

**Comment by marcandre** [comment]
Sorry about that, @tilthouse, not sure what I did wrong, but should be good now.
